// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace POC.DataLayer.Models;

public partial class DemoProjectContext : DbContext
{
    public DemoProjectContext(DbContextOptions<DemoProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddressDetail> AddressDetails { get; set; }

    public virtual DbSet<CartOrder> CartOrders { get; set; }

    public virtual DbSet<CartTable> CartTables { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Refreshtoken> Refreshtokens { get; set; }

    public virtual DbSet<TemporderTable> TemporderTables { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddressDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AddressD__3214EC079B30672F");

            entity.Property(e => e.IsDefault).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<CartOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CartOrde__3214EC07C65C0BF9");
        });

        modelBuilder.Entity<CartTable>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__CartTabl__51BCD7B796CCBBCD");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Id");

            entity.Property(e => e.MobileNumber).IsFixedLength();
            entity.Property(e => e.Postcode).IsFixedLength();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK_OrderId");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC0717502D65");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK_ProductId");
        });

        modelBuilder.Entity<Refreshtoken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__refresht__3213E83F9469E7F6");
        });

        modelBuilder.Entity<TemporderTable>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__temporde__C3905BCFDC8E240C");

            entity.Property(e => e.OrderId).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}