// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using POC.DomainModel.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace POC.DomainModel.Models
{
    public partial interface IDemoProjectContextProcedures
    {
        Task<List<GetProductsResult>> GetProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetProductsByIdResult>> GetProductsByIdAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetProductsByNameResult>> GetProductsByNameAsync(string SearchName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
