// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DomainModel.Models;

[Table("CartTable")]
public partial class CartTable
{
    [Key]
    public int CartId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public int? Quantity { get; set; }
}