// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DomainModel.Models;

public partial class Login
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Password { get; set; }

    [Required]
    public string Email { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [InverseProperty("IdNavigation")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}