// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DataLayer.Models;

public partial class Login
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Password { get; set; }

    [Required]
    public string Email { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [StringLength(100)]
    public string Surname { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MobileNumber { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string Postcode { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    [StringLength(50)]
    public string Country { get; set; }
}