// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DomainModel.Models;

[Index("ProductId", Name = "IX_Orders_ProductId")]
public partial class Order
{
    [Key]
    public int OrderId { get; set; }

    public DateTime OrderDate { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public int? Id { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OrderPrice { get; set; }
}