// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DomainModel.Models;

[Table("refreshtoken")]
public partial class Refreshtoken
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("expiration_time", TypeName = "datetime")]
    public DateTime ExpirationTime { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string RefreshToken1 { get; set; }
}