// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POC.DomainModel.Models;

[Table("temporderTable")]
public partial class TemporderTable
{
    [Key]
    public int OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? OrderPrice { get; set; }
}